/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies/index'
import { Route as SolutionsItRouteImport } from './routes/solutions/it'
import { Route as SolutionsEtrmCtrmRouteImport } from './routes/solutions/etrm-ctrm'
import { Route as SolutionsCyberSecurityRouteImport } from './routes/solutions/cyber-security'
import { Route as InsightsResourceRouteImport } from './routes/insights/resource'
import { Route as CaseStudiesCaseIdRouteImport } from './routes/case-studies/$caseId'

const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsItRoute = SolutionsItRouteImport.update({
  id: '/solutions/it',
  path: '/solutions/it',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsEtrmCtrmRoute = SolutionsEtrmCtrmRouteImport.update({
  id: '/solutions/etrm-ctrm',
  path: '/solutions/etrm-ctrm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCyberSecurityRoute = SolutionsCyberSecurityRouteImport.update({
  id: '/solutions/cyber-security',
  path: '/solutions/cyber-security',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsResourceRoute = InsightsResourceRouteImport.update({
  id: '/insights/resource',
  path: '/insights/resource',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesCaseIdRoute = CaseStudiesCaseIdRouteImport.update({
  id: '/case-studies/$caseId',
  path: '/case-studies/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/case-studies/$caseId': typeof CaseStudiesCaseIdRoute
  '/insights/resource': typeof InsightsResourceRoute
  '/solutions/cyber-security': typeof SolutionsCyberSecurityRoute
  '/solutions/etrm-ctrm': typeof SolutionsEtrmCtrmRoute
  '/solutions/it': typeof SolutionsItRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/case-studies/$caseId': typeof CaseStudiesCaseIdRoute
  '/insights/resource': typeof InsightsResourceRoute
  '/solutions/cyber-security': typeof SolutionsCyberSecurityRoute
  '/solutions/etrm-ctrm': typeof SolutionsEtrmCtrmRoute
  '/solutions/it': typeof SolutionsItRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/case-studies/$caseId': typeof CaseStudiesCaseIdRoute
  '/insights/resource': typeof InsightsResourceRoute
  '/solutions/cyber-security': typeof SolutionsCyberSecurityRoute
  '/solutions/etrm-ctrm': typeof SolutionsEtrmCtrmRoute
  '/solutions/it': typeof SolutionsItRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/case-studies/$caseId'
    | '/insights/resource'
    | '/solutions/cyber-security'
    | '/solutions/etrm-ctrm'
    | '/solutions/it'
    | '/case-studies'
    | '/insights'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/case-studies/$caseId'
    | '/insights/resource'
    | '/solutions/cyber-security'
    | '/solutions/etrm-ctrm'
    | '/solutions/it'
    | '/case-studies'
    | '/insights'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/case-studies/$caseId'
    | '/insights/resource'
    | '/solutions/cyber-security'
    | '/solutions/etrm-ctrm'
    | '/solutions/it'
    | '/case-studies/'
    | '/insights/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  CaseStudiesCaseIdRoute: typeof CaseStudiesCaseIdRoute
  InsightsResourceRoute: typeof InsightsResourceRoute
  SolutionsCyberSecurityRoute: typeof SolutionsCyberSecurityRoute
  SolutionsEtrmCtrmRoute: typeof SolutionsEtrmCtrmRoute
  SolutionsItRoute: typeof SolutionsItRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/it': {
      id: '/solutions/it'
      path: '/solutions/it'
      fullPath: '/solutions/it'
      preLoaderRoute: typeof SolutionsItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/etrm-ctrm': {
      id: '/solutions/etrm-ctrm'
      path: '/solutions/etrm-ctrm'
      fullPath: '/solutions/etrm-ctrm'
      preLoaderRoute: typeof SolutionsEtrmCtrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cyber-security': {
      id: '/solutions/cyber-security'
      path: '/solutions/cyber-security'
      fullPath: '/solutions/cyber-security'
      preLoaderRoute: typeof SolutionsCyberSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/resource': {
      id: '/insights/resource'
      path: '/insights/resource'
      fullPath: '/insights/resource'
      preLoaderRoute: typeof InsightsResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$caseId': {
      id: '/case-studies/$caseId'
      path: '/case-studies/$caseId'
      fullPath: '/case-studies/$caseId'
      preLoaderRoute: typeof CaseStudiesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  CaseStudiesCaseIdRoute: CaseStudiesCaseIdRoute,
  InsightsResourceRoute: InsightsResourceRoute,
  SolutionsCyberSecurityRoute: SolutionsCyberSecurityRoute,
  SolutionsEtrmCtrmRoute: SolutionsEtrmCtrmRoute,
  SolutionsItRoute: SolutionsItRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
